#!/bin/bash

source /etc/syncfrom.conf

echo
printf 'Input address of remotePC (Ex.: user@10.1.2.5): ' && read remotePC
printf 'Input ssh-port of remotePC (Ex.: 22): ' && read remotePC_port
printf 'Input path to sync-directory of remotePC (Ex.: /home/user): ' && read remotePC_path

export syncFrom_host=$remotePC
export syncFrom_port=$remotePC_port
export syncFrom_path=$remotePC_path
export syncTo_host=localhost
export syncTo_port=22
export syncTo_path=$path_pc
.syncfrom_general
