#!/bin/bash

source /etc/syncfrom.conf

echo
echo -e "snaifServer:"
echo -e "\taddress = $snaifServer_addr"
echo -e "\tport = $snaifServer_port"
echo -e "\tpath = $snaifServer_path"

export remotePC="$snaifServer_addr"
export remotePC_port="$snaifServer_port"
export remotePC_path="$snaifServer_path"

export syncFrom_host=$remotePC
export syncFrom_port=$remotePC_port
export syncFrom_path=$remotePC_path
export syncTo_host=localhost
export syncTo_port=22
export syncTo_path=$path_pc
.syncfrom_general
