#!/bin/bash

source /etc/syncfrom.conf

export syncFrom_host=""
export syncFrom_port=""
export syncFrom_path=$path_pc
export syncTo_host=""
export syncTo_port=""
export syncTo_path=$path_disk
.syncfrom_general