#!/bin/bash

source /etc/syncfrom.conf

sudo hamachi list
echo
printf 'Input address of remotePC (Ex.: user@10.1.2.5): ' && read remotePC
printf 'Input ssh-port of remotePC (Ex.: 22): ' && read remotePC_port
printf 'Input path to sync-directory of remotePC (Ex.: /home/user): ' && read remotePC_path

.syncfrom_remotePC_pc
