#!/bin/bash

source /etc/syncfrom.conf

echo
echo -e "snaifServer:"
echo -e "\taddress = $snaifServer_addr"
echo -e "\tport = $snaifServer_port"
echo -e "\tpath = $snaifServer_path"

export remotePC="$snaifServer_addr"
export remotePC_port="$snaifServer_port"
export remotePC_path="$snaifServer_path"

export syncFrom_host=localhost
export syncFrom_port=22
export syncFrom_path=""
export syncTo_host=$remotePC
export syncTo_port=$remotePC_port
export syncTo_path=$remotePC_path
.syncfrom_general
