#!/bin/bash

source /etc/syncfrom.conf

echo
printf 'Input address of remotePC (Ex.: user@10.1.2.5): ' && read remotePC
printf 'Input ssh-port of remotePC (Ex.: 22): ' && read remotePC_port
printf 'Input path to sync-directory of remotePC (Ex.: /home/user): ' && read remotePC_path

export syncFrom_host=localhost
export syncFrom_port=22
export syncFrom_path=""
export syncTo_host=$remotePC
export syncTo_port=$remotePC_port
export syncTo_path=$remotePC_path
.syncfrom_general
